os: linux
language: python
python:
- '3.6'
install:
- pip install -r requirements-dev.txt
script:
- make flake
deploy:
  provider: pypi
  user: __token__
  on:
    branch: master
    tags: true
  password:
    secure: wxtxTMJmESWjpDkg68Vq9B84rSC39BWnfQKq0Uq1FfrZgUVftfVCSjjX6e93CFZER+QesdL9DU4BJfLr+wGtnADSIf4/F9uHXK3z6J0f6I9I7+B/E2e+iZ+hzhojsRBJoktDXyCUOEcr2/JdwzKpj16Rh3D4ekzshpWLdfgp9SrtPgE4BfEElAp0+NsUEmL+GhYYd8MGq9a/cjH7aMm5DYBtzYMKuruVoBEkK5F0xqLiNpU7YVAdQAdPj/884axWyXw/+tueVLbED7x+R20fA0tJVpHodp3fZjgVBX/4h2N/D35j4PxDSyCkON8FX1Dt4YGYBOqkR0jtXFEx2H55dngow3Ffxa8IyWukp9wLGSqSqVTFGDGeJH73vPmMQv05rMoWjz3jqO6uG5psg6Lyzh+Xd9xCo5MMeAFQ0Kh/vwPNG9Kwaa2gSvZqF2F87jjr8Gq5cyxbcOELsriHmOC+uVWPbksvzLmdeetMtRQW6Bew6K0/GOLIBbZEwegOYBibay8n7JYWIOTBdxdvNw6DtXK1N/j8gt6J80pp3myEh8/4PTN+jt33C96CdtaMHM90GA+m3cXVtO2BXqioImsbdpKmnls8zRtTn0Geq0x81V9gto51BlEIluYnzfb5A02ZzvMMn83eD5QlaHDpccs4YTCiR0avJeRFuzLJmwN14W4=
